language: python

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements_pip.txt
  - pip install flake8 coverage

script:
  - coverage run -m py.test && coverage report && coverage html -d build/coverage
  - flake8 reporter/ --exit-zero
